Update message

diff --git a/.github/workflows/publish_tagged.yaml b/.github/workflows/publish_tagged.yaml
--- a/.github/workflows/publish_tagged.yaml
+++ b/.github/workflows/publish_tagged.yaml
@@ -49,7 +49,7 @@ jobs:
           '(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
           )
           if [[ "$drand_version" != "$tag_version" ]]; then
-            >&2 echo "Error unexpected binary version $drand_version found on tag $tag_version"
+            >&2 echo "Error unexpected binary version $drand_version found on for git tag $tag_version"
             exit 1
           fi
       - uses: actions/setup-go@v5
