Add binary version validation step on release

diff --git a/.github/workflows/publish_tagged.yaml b/.github/workflows/publish_tagged.yaml
--- a/.github/workflows/publish_tagged.yaml
+++ b/.github/workflows/publish_tagged.yaml
@@ -24,7 +24,15 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-
+      - name: Validate drand binary version matches git tag for this release
+        shell: bash
+        run: |
+          drand_version=$(docker run -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }} -v | awk '{ print "v" $2 }')
+          drand_tag=$(git describe --tags |  grep -P '^v(?P<major>0|[1-9]\d*)\.(?P<minor>0|[1-9]\d*)\.(?P<patch>0|[1-9]\d*)(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$)
+          if [[ "$drand_version" != "$tag_version" ]]; then
+            >&2 echo "Error unexpected binary version $drand_version found on tag $drand_tag"
+            exit 1
+          fi
       - uses: actions/setup-go@v5
         with:
           go-version: '1.22.1'
